apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana
  namespace: prometheus
data:
  grafana.ini: |
    [server]
    domain = grafana.gokuladethya.uk
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    hide_version = true
    device_limit = 100
    
    [feature_toggles]
    enable = displayAnonymousStats
















